[package]
name = "bigfish"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }
sdl3 = { version = "0.17.1", features = ["raw-window-handle"] }

[build-dependencies]
bindgen = "0.72.1"
