[package]
name = "bigfish"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }
thiserror = "2.0.16"

[build-dependencies]
bindgen = "0.72.1"
